In [1]:
import numpy as np
import pandas as pd
from os import listdir
from os.path import isfile, join
import warnings
warnings.filterwarnings('ignore')

In [53]:
folder = ''
temp1 = pd.read_csv(folder+'Task1_step4.csv')
players = list(set(temp1['participant_ID'].to_list()))

In [62]:
t1 = np.array([[int(i),0] for i in players])
for key,value in temp1.iterrows():
    if value[7] == 1:
        if value[-2] == value[-3]:
            t1[list(t1[:,0]).index(value[0]),1] += 1000

In [63]:
print(t1)

[[    1 23000]
 [    2 20000]
 [    3 22000]
 [    4 19000]
 [    5 20000]
 [    6 24000]
 [    7 21000]
 [    8 20000]
 [    9 23000]
 [   10 20000]
 [   11 21000]
 [   12 23000]
 [   13 15000]
 [   14 21000]]


In [84]:
temp2 = pd.read_csv(folder+'Task2_step4.csv')
players = list(set(temp2['participant_ID'].to_list()))

In [85]:
t2 = np.array([[int(i),500] for i in players])
for key,value in temp2.iterrows():
    if value[7] == 1:
        if value[-2] == value[-3]:
            t2[list(t2[:,0]).index(value[0]),1] += 1000 - value[4]*value[10] - value[5]*value[11]

In [86]:
print(t2)

[[    1 18500]
 [    2  9500]
 [    3 25500]
 [    4 17500]
 [    5 15500]
 [    6 21500]
 [    7  3500]
 [    8 21500]
 [    9 16500]
 [   10 12500]
 [   11 21500]
 [   12  8500]
 [   13 19500]
 [   14 23500]]


In [94]:
temp3 = pd.read_csv(folder+'Task3_step4.csv')
players = list(set(temp3['participant_ID'].to_list()))

In [95]:
t3 = np.array([[int(i),500] for i in players])
for key,value in temp3.iterrows():
    if value[7] == 1:
        if value[-2] == value[-3]:
            t3[list(t3[:,0]).index(value[0]),1] += 1000 + value[4]*value[10] - value[5]*value[11]

In [96]:
print(t3)

[[    1 42500]
 [    2 16500]
 [    3 47500]
 [    4 33500]
 [    5 25500]
 [    6 46500]
 [    7   500]
 [    8 46500]
 [    9 37500]
 [   10 22500]
 [   11 47500]
 [   12 15500]
 [   13 43500]
 [   14 45500]]


In [102]:
df = pd.DataFrame(t3, columns=['participant_ID', 'task_3'])
df['task_2'] = t2[:,1]
df['task_1'] = t1[:,1]

In [103]:
df.to_csv('payoff.csv', index=False)