In [9]:
import numpy as np
import pandas as pd
from os import listdir
from os.path import isfile, join
import warnings
warnings.filterwarnings('ignore')

In [10]:
oloc = open("../Output_Location.txt", "r").read()
temp1 = pd.read_csv(oloc+'Task1_step4.csv')
players = list(set(temp1['participant_ID'].to_list()))

In [11]:
t1 = np.array([[int(i),0] for i in players])
for key,value in temp1.iterrows():
    if value[7] == 1:
        if value[-2] == value[-3]:
            t1[list(t1[:,0]).index(value[0]),1] += 1000

In [12]:
print(t1)

[[    1 21000]
 [    2 21000]
 [    3 22000]
 [    4 23000]
 [    5 18000]
 [    6 20000]
 [    7 20000]
 [    8 19000]
 [    9 21000]
 [   10 19000]
 [   11 17000]
 [   12 21000]
 [   13 15000]
 [   14 20000]
 [   15 22000]
 [   16 23000]
 [   17 22000]
 [   18 22000]
 [   19 23000]
 [   20 21000]
 [   21 22000]
 [   22 22000]
 [   23 21000]
 [   24 18000]
 [   25 23000]
 [   26 24000]
 [   27 20000]
 [   28 19000]
 [   29 22000]
 [   30 23000]
 [   31 22000]
 [   32 20000]
 [   33 19000]
 [   34 21000]
 [   35 20000]
 [   36 20000]
 [   37 12000]
 [   38 19000]
 [   39 18000]
 [   40 17000]
 [   41 22000]
 [   42 23000]
 [   43 13000]
 [   44 22000]
 [   45 22000]
 [   46 15000]
 [   47 20000]
 [   48 22000]
 [   49 19000]
 [   50 20000]
 [   51 22000]
 [   52 22000]
 [   53 24000]
 [   54 19000]
 [   55 19000]
 [   56 16000]
 [   57 17000]
 [   58 18000]
 [   59 12000]
 [   60 19000]
 [   61 21000]
 [   62 21000]
 [   63 17000]
 [   64 23000]
 [   65 21000]
 [   66 21000]
 [   67 19

In [13]:
temp2 = pd.read_csv(oloc+'Task2_step4.csv')
players = list(set(temp2['participant_ID'].to_list()))

In [14]:
t2 = np.array([[int(i),500] for i in players])
for key,value in temp2.iterrows():
    if value[7] == 1:
        if value[-2] == value[-3]:
            t2[list(t2[:,0]).index(value[0]),1] += 1000 - value[4]*value[10] - value[5]*value[11]
        else:
            t2[list(t2[:,0]).index(value[0]),1] += value[4]*value[10] - value[5]*value[11]

In [15]:
print(t2)

[[    1 17500]
 [    2 23500]
 [    3 18500]
 [    4 23500]
 [    5 23500]
 [    6 21500]
 [    7 20500]
 [    8 25500]
 [    9 20500]
 [   10 24500]
 [   11 24500]
 [   12 23500]
 [   13 19500]
 [   14 18500]
 [   15 21500]
 [   16 21500]
 [   17 21500]
 [   18 24500]
 [   19 19500]
 [   20 21500]
 [   21 21500]
 [   22 20500]
 [   23 24500]
 [   24 25500]
 [   25 21500]
 [   26 22500]
 [   27 25500]
 [   28 24500]
 [   29 23500]
 [   30 21500]
 [   31 18500]
 [   32 23500]
 [   33 10500]
 [   34 20500]
 [   35 24500]
 [   36 19500]
 [   37 22500]
 [   38 23500]
 [   39 21500]
 [   40 23500]
 [   41 18500]
 [   42 23500]
 [   43 23500]
 [   44 23500]
 [   45 23500]
 [   46 15500]
 [   47 23500]
 [   48 19500]
 [   49 17500]
 [   50 24500]
 [   51 23500]
 [   52 25500]
 [   53 23500]
 [   54 22500]
 [   55 21500]
 [   56 23500]
 [   57 17500]
 [   58 25500]
 [   59 17500]
 [   60 22500]
 [   61 22500]
 [   62 20500]
 [   63 19500]
 [   64 24500]
 [   65 18500]
 [   66 23500]
 [   67 21

In [16]:
temp3 = pd.read_csv(oloc+'Task3_step4.csv')
players = list(set(temp3['participant_ID'].to_list()))

In [17]:
t3 = np.array([[int(i),500] for i in players])
for key,value in temp3.iterrows():
    if value[7] == 1:
        if value[-2] == value[-3]:
            t3[list(t3[:,0]).index(value[0]),1] += 1000 + value[4]*value[10] - value[5]*value[11]
        else:
            t3[list(t3[:,0]).index(value[0]),1] += value[4]*value[10] - value[5]*value[11]

In [18]:
print(t3)

[[    1 42500]
 [    2 50500]
 [    3 41500]
 [    4 43500]
 [    5 43500]
 [    6 38500]
 [    7 35500]
 [    8 48500]
 [    9 41500]
 [   10 46500]
 [   11 40500]
 [   12 43500]
 [   13 42500]
 [   14 35500]
 [   15 44500]
 [   16 38500]
 [   17 42500]
 [   18 48500]
 [   19 46500]
 [   20 39500]
 [   21 47500]
 [   22 40500]
 [   23 49500]
 [   24 47500]
 [   25 41500]
 [   26 42500]
 [   27 47500]
 [   28 49500]
 [   29 47500]
 [   30 48500]
 [   31 38500]
 [   32 47500]
 [   33 26500]
 [   34 34500]
 [   35 49500]
 [   36 36500]
 [   37 44500]
 [   38 45500]
 [   39 45500]
 [   40 44500]
 [   41 36500]
 [   42 47500]
 [   43 47500]
 [   44 48500]
 [   45 48500]
 [   46 37500]
 [   47 39500]
 [   48 45500]
 [   49 37500]
 [   50 42500]
 [   51 45500]
 [   52 43500]
 [   53 48500]
 [   54 44500]
 [   55 47500]
 [   56 40500]
 [   57 39500]
 [   58 46500]
 [   59 36500]
 [   60 47500]
 [   61 45500]
 [   62 44500]
 [   63 36500]
 [   64 47500]
 [   65 40500]
 [   66 48500]
 [   67 38

In [19]:
df = pd.DataFrame(t3, columns=['participant_ID', 'task_3'])
df['task_2'] = t2[:,1]
df['task_1'] = t1[:,1]

In [20]:
df.to_csv(oloc+'payoff.csv', index=False)